spring.datasource.url=jdbc:postgresql://localhost:5433/task_db
#PostgreSQL yerel localhost değeri 5432
spring.datasource.username=postgres
spring.datasource.password=Sevval
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.type.deescriptor.sql.BasicBinder=TRACE
